package zollerngalaxy.core.enums;

public enum EnumBlockType {
	
	GRASS, DIRT, STONE, COBBLESTONE, METAL, ORE, NORMAL, FLOWER, SAND, GRAVEL, WOOD, LEAVES, SAPLING, FRUIT, COMPRESSED, SHINE, GLASS, CANDY, SWEET, SPACE;
	
}